# -----------------------------------------------------------------------
# configs/Derexyl/EczemaPred/t_horizon_1/derexyl_dryness_orderedrw.yaml
# -----------------------------------------------------------------------

# Dataset and target -----------------------------------------------------

dataset: "Derexyl"          # Derexyl | PFDC | Fake
score: "dryness"            # extent | dryness | redness | swelling | oozing | thickening | scratching | itching | sleep
model: "OrderedRW"          # BinMC | OrderedRW | BinRW

# Forward-chaining setup -------------------------------------------------

t_horizon: 1                # Forecast/update horizon

# Stan/MCMC settings -----------------------------------------------------

n_chains: 4                 # Number of Stan chains per model fit
n_iter: 2000                # Number of MCMC iterations per chain

# Parallelisation --------------------------------------------------------

n_cluster: 15

# Run mode ---------------------------------------------------------------

run: true                   # If false, only checks config and prepares paths
fit_only: false              # If true, only fits final iteration to extract power priors
debug_one_patient: false    # If true, run only one patient for debugging
